[site]
title = "/dev/lsck0"
description = "mathematics and software engineering"
author = "Luca Sandrock"
url = "https://lsck0.github.io"

[pages.home]
title = "/dev/lsck0"
description = "mathematics and software engineering"

[pages.about]
title = "about"
description = "mathematics and software engineering"

[pages.blog]
title = "blog"
description = "mathematics and software engineering"

[pages.projects]
title = "projects"
description = "mathematics and software engineering"

[pages.publications]
title = "publications"
description = "mathematics and software engineering"

[pages.graph]
title = "knowledge graph"
description = "mathematics and software engineering"
