[[publications]]
authors = "Komal Abbas, Luca Sandrock, Barbara Hanfstingl"
title = [{ scrambled = 20 }]
description = [{ scrambled = 70 }]
date = "2026"

[[publications]]
title = "Topological Complexity of Symplectic CW-Complexes"
description = """
  A cohomology class $u$ of a topological space $X$ is atoroidal if its pullback to the torus vanishes for every
  map from a torus to $X$. Furthermore, a CW-complex $X$ of dimension $2n$ is called atoroidally symplectic if there
  exists an atoroidal cohomology class $u\\in H^2_{sing}(X; F)$ (for some coefficient field $F$ with either
  $\\char(F)=0$ or $\\char(F)>2n$) such that $u^n \\not = 0$.
  We prove that every atoroidally symplectic CW-complex $X$ of dimension $2n$ has topological complexity $4n$.
  This generalizes a result of Grant and Mescher who prove the corresponding statement in the case where $X$ is an
  atoroidally c-symplectic manifold and $u$ is a de Rham cohomology class.
  Using this generalisation, we obtain new calculations of topological complexity, including for many
  products of 3-manifolds and of group presentation complexes.
"""
url = "https://arxiv.org/abs/2505.19324"
authors = "Luca Sandrock, Thomas Schick"
date = "25 May 2025"
